# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1.7/stdlib/LinearAlgebra/#man-linalg

In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::StridedMatrix{T}) where T in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:1302
[2] factorize(A::Adjoint) in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:1376
[3] factorize(A::Transpose) in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:1377
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/triangular.jl:2569
[5] factorize(A::Tridiagonal) in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/lu.jl:567
[6] factorize(D::Diagonal) in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/diagonal.jl:137
[7] factorize(A::Bidiagonal) in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/bidiag.jl:845
[8] factorize(S::SymTridiagonal) in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/ldlt.jl:170
[9] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at /opt/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/linalg.jl:1586
[10] factorize(A::Union{Hermitian{ComplexF64, var"#s859"}, Hermitian{Float64, var"#s859"}, Symmetric{Float64, var"#s859"}} where var"#s859"<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at /opt/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/linalg.jl:1616
[11] factorize(A::Union{Hermitian{T, S}, Symmetric{T, S}} where {T, S}) in LinearAlgebra at /opt/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/symmetric.jl:641

In [3]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Matrix{Int64}:
 1  2  2

In [4]:
y1=[1 ;2 ;3]

3-element Vector{Int64}:
 1
 2
 3

In [5]:
transpose(x1)

3×1 transpose(::Matrix{Int64}) with eltype Int64:
 1
 2
 2

In [6]:
#iloczyn skalarny
dot(x1,y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [7]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Matrix{Float64}:
 0.338022  0.696689  0.794447
 0.292909  0.10343   0.762553
 0.495313  0.328252  0.611743

In [8]:
#losujemy wektor x
x=rand(3)

3-element Vector{Float64}:
 0.3780372286247057
 0.37606084506049897
 0.8866804824490215

In [9]:
# wyliczamy b
b=A*x

3-element Vector{Float64}:
 1.0942033548713916
 0.8257671166994867
 0.8531095970634283

### Sposoby rozwiązania Ax=b

In [10]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Vector{Float64}:
 0.3780372286247057
 0.3760608450604992
 0.8866804824490216

In [11]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Vector{Float64}:
 0.37803722862470557
 0.37606084506049914
 0.8866804824490215

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.7/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.7/stdlib/LinearAlgebra/#man-linalg-factorizations
 


### Faktoryzacja LU

In [12]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64, Matrix{Float64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.682442   1.0       0.0
 0.591362  -0.191856  1.0
U factor:
3×3 Matrix{Float64}:
 0.495313  0.328252  0.611743
 0.0       0.472677  0.376969
 0.0       0.0       0.473115

In [13]:
# Macierz L
Af.L

3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.682442   1.0       0.0
 0.591362  -0.191856  1.0

In [14]:
# Macierz U
Af.U

3×3 Matrix{Float64}:
 0.495313  0.328252  0.611743
 0.0       0.472677  0.376969
 0.0       0.0       0.473115

In [15]:
# wektor permutatacji wierszy 
Af.p

3-element Vector{Int64}:
 3
 1
 2

In [16]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A = factorize(A)

LU{Float64, Matrix{Float64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.682442   1.0       0.0
 0.591362  -0.191856  1.0
U factor:
3×3 Matrix{Float64}:
 0.495313  0.328252  0.611743
 0.0       0.472677  0.376969
 0.0       0.0       0.473115

In [17]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Vector{Float64}:
 0.37803722862470557
 0.37606084506049914
 0.8866804824490215

In [18]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Vector{Float64}:
  1.040823229139649
  0.656086484780959
 -0.1643365439575074

### Faktoryzacja QR


In [19]:
B = rand(10,5)

10×5 Matrix{Float64}:
 0.976341   0.904916  0.827044   0.973285   0.874551
 0.012195   0.245964  0.666299   0.941011   0.16332
 0.692038   0.637657  0.196204   0.798878   0.755658
 0.516523   0.260224  0.176538   0.710576   0.368137
 0.229555   0.216178  0.450712   0.630714   0.362074
 0.657359   0.645472  0.0972128  0.668244   0.00671323
 0.420609   0.836887  0.91395    0.79869    0.325329
 0.876273   0.296096  0.636216   0.960865   0.717016
 0.0527586  0.498327  0.0824871  0.0750253  0.079666
 0.0620897  0.575294  0.252384   0.228782   0.736203

In [20]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64, Matrix{Float64}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64, Matrix{Float64}}:
 -0.417316    0.288537  -0.218617   …  -0.449822   -0.0637756  -0.0758489
 -0.403477   -0.370668   0.29584       -0.182277    0.17148     0.0204027
 -0.342535    0.128271  -0.271055      -0.184276    0.0376699  -0.566652
 -0.304674   -0.202957  -0.0271974     -0.309309    0.158408    0.495756
 -0.270431   -0.195433  -0.071875       0.435456   -0.399911   -0.374385
 -0.286523    0.22307    0.550582   …   0.272811   -0.323783    0.191323
 -0.342455    0.334181   0.319137      -0.0316712  -0.0954532   0.0199915
 -0.41199    -0.332067  -0.316728       0.496471    0.311108    0.16103
 -0.0321686   0.464914   0.163326       0.287671    0.721933   -0.141876
 -0.0980949   0.442337  -0.503317       0.201288   -0.219464    0.451369
R factor:
5×5 Matrix{Float64}:
 -2.33225  -1.49903   -1.38329   -1.57005   -1.48722
  0.0       0.968147   0.378061   0.264472   0.158743
  0.0       0.0       -0.86

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- W postaci macierzowej: $$A*wsp=y$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

 punkty $(x_i,y_i)$


In [21]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Vector{Int64}:
 1
 2
 4
 4
 3
 0

In [22]:
A = zeros(6,3) 

6×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [23]:
A[:,1]=x.^2

6-element Vector{Int64}:
  1
  4
  9
 16
 25
 36

In [24]:
A[:,2]=x

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [25]:
A[:,3]=ones(6)

6-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
A

6×3 Matrix{Float64}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [27]:
AF = factorize(A)

QRPivoted{Float64, Matrix{Float64}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64, Matrix{Float64}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Matrix{Float64}:
 -47.697  -9.24587  -1.90788
   0.0    -2.34816  -1.43091
   0.0     0.0       0.559017
permutation:
3-element Vector{Int64}:
 1
 2
 3

In [28]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Matrix{Float64}:
  1.0           0.0           1.66533e-16  …   2.77556e-17  -2.77556e-17
  0.0           1.0           5.55112e-17      8.32667e-17  -9.71445e-17
  1.66533e-16   5.55112e-17   1.0             -6.93889e-17  -2.77556e-17
 -2.08167e-17  -4.85723e-17  -7.97973e-17     -6.59195e-17  -3.1225e-17
  2.77556e-17   8.32667e-17  -6.93889e-17      1.0          -2.77556e-17
 -2.77556e-17  -9.71445e-17  -2.77556e-17  …  -2.77556e-17   1.0

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [29]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Vector{Float64}:
 -0.5714285714285724
  3.94285714285715
 -2.8000000000000145

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [30]:
A \ y

3-element Vector{Float64}:
 -0.5714285714285723
  3.9428571428571493
 -2.8000000000000136

In [31]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
fit(x,y, 2)

Polynomial(-2.8000000000000136 + 3.9428571428571493*x - 0.5714285714285723*x^2)

In [32]:
@which fit

Polynomials

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/master/src/common.jl#L142">
fit</a>  z pakietu Polynomials używa własnie tej metody


### Zadania

#### Zadanie 1 (1pkt)
Ustal losowe (referencyjne) `x` rozmiaru 1000 oraz losowe `A` rozmiaru 1000x1000, policz `b=A*x`.
Nastepnie rozwiąż równanie `Ax=b` trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego `x`) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania!

#### Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3 (2 pkt)

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

- uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

- zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254

- kompresji danych https://medium.com/balabit-unsupervised/image-compression-using-singular-value-decomposition-de20451c69a3
